// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function ArchiveDelete(arg1, arg2) {
  return window['go']['main']['App']['ArchiveDelete'](arg1, arg2);
}

export function ArchiveList(arg1) {
  return window['go']['main']['App']['ArchiveList'](arg1);
}

export function ArchiveOpen(arg1) {
  return window['go']['main']['App']['ArchiveOpen'](arg1);
}

export function ArchiveSave(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ArchiveSave'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CachedMessages(arg1, arg2) {
  return window['go']['main']['App']['CachedMessages'](arg1, arg2);
}

export function CalendarDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalendarDelete'](arg1, arg2, arg3);
}

export function CalendarList(arg1) {
  return window['go']['main']['App']['CalendarList'](arg1);
}

export function CalendarSave(arg1, arg2) {
  return window['go']['main']['App']['CalendarSave'](arg1, arg2);
}

export function CancelScheduled(arg1) {
  return window['go']['main']['App']['CancelScheduled'](arg1);
}

export function CheckMTASTS(arg1) {
  return window['go']['main']['App']['CheckMTASTS'](arg1);
}

export function CheckRecipientDANE(arg1, arg2) {
  return window['go']['main']['App']['CheckRecipientDANE'](arg1, arg2);
}

export function CheckRecipientTLS(arg1) {
  return window['go']['main']['App']['CheckRecipientTLS'](arg1);
}

export function ContactDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['ContactDelete'](arg1, arg2, arg3);
}

export function ContactList(arg1) {
  return window['go']['main']['App']['ContactList'](arg1);
}

export function ContactSave(arg1, arg2) {
  return window['go']['main']['App']['ContactSave'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2);
}

export function Delete(arg1, arg2, arg3) {
  return window['go']['main']['App']['Delete'](arg1, arg2, arg3);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function ExportSettings() {
  return window['go']['main']['App']['ExportSettings']();
}

export function Folders(arg1) {
  return window['go']['main']['App']['Folders'](arg1);
}

export function GetAttachmentData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAttachmentData'](arg1, arg2, arg3, arg4);
}

export function GetAttachmentText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAttachmentText'](arg1, arg2, arg3, arg4);
}

export function GetAutostart() {
  return window['go']['main']['App']['GetAutostart']();
}

export function GetWindowMode() {
  return window['go']['main']['App']['GetWindowMode']();
}

export function ImportSettings(arg1) {
  return window['go']['main']['App']['ImportSettings'](arg1);
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function ListScheduled() {
  return window['go']['main']['App']['ListScheduled']();
}

export function MailcowAddAlias(arg1, arg2) {
  return window['go']['main']['App']['MailcowAddAlias'](arg1, arg2);
}

export function MailcowAddAppPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['MailcowAddAppPassword'](arg1, arg2, arg3);
}

export function MailcowAliases(arg1) {
  return window['go']['main']['App']['MailcowAliases'](arg1);
}

export function MailcowAppPasswords(arg1) {
  return window['go']['main']['App']['MailcowAppPasswords'](arg1);
}

export function MailcowDeleteAlias(arg1, arg2) {
  return window['go']['main']['App']['MailcowDeleteAlias'](arg1, arg2);
}

export function MailcowDeleteAppPassword(arg1, arg2) {
  return window['go']['main']['App']['MailcowDeleteAppPassword'](arg1, arg2);
}

export function MailcowQuarantine(arg1) {
  return window['go']['main']['App']['MailcowQuarantine'](arg1);
}

export function MailcowQuarantineAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['MailcowQuarantineAction'](arg1, arg2, arg3);
}

export function MailcowQuarantineDelete(arg1, arg2) {
  return window['go']['main']['App']['MailcowQuarantineDelete'](arg1, arg2);
}

export function MailcowQuota(arg1) {
  return window['go']['main']['App']['MailcowQuota'](arg1);
}

export function MailcowSetAliasGoto(arg1, arg2, arg3) {
  return window['go']['main']['App']['MailcowSetAliasGoto'](arg1, arg2, arg3);
}

export function MailcowTest(arg1, arg2) {
  return window['go']['main']['App']['MailcowTest'](arg1, arg2);
}

export function Message(arg1, arg2, arg3) {
  return window['go']['main']['App']['Message'](arg1, arg2, arg3);
}

export function MessageSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['MessageSource'](arg1, arg2, arg3);
}

export function Messages(arg1, arg2) {
  return window['go']['main']['App']['Messages'](arg1, arg2);
}

export function MessagesPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['MessagesPage'](arg1, arg2, arg3);
}

export function Move(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Move'](arg1, arg2, arg3, arg4);
}

export function OpenMailWindow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['OpenMailWindow'](arg1, arg2, arg3, arg4, arg5);
}

export function PGPDecryptBody(arg1, arg2) {
  return window['go']['main']['App']['PGPDecryptBody'](arg1, arg2);
}

export function PGPDeleteKey(arg1) {
  return window['go']['main']['App']['PGPDeleteKey'](arg1);
}

export function PGPEncryptBody(arg1, arg2) {
  return window['go']['main']['App']['PGPEncryptBody'](arg1, arg2);
}

export function PGPImportKey(arg1) {
  return window['go']['main']['App']['PGPImportKey'](arg1);
}

export function PGPListKeys() {
  return window['go']['main']['App']['PGPListKeys']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function Probe(arg1) {
  return window['go']['main']['App']['Probe'](arg1);
}

export function RemoveAccount(arg1) {
  return window['go']['main']['App']['RemoveAccount'](arg1);
}

export function RenameFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2, arg3);
}

export function SaveAttachment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAttachment'](arg1, arg2, arg3, arg4);
}

export function SaveDraft(arg1, arg2) {
  return window['go']['main']['App']['SaveDraft'](arg1, arg2);
}

export function ScheduleSend(arg1, arg2) {
  return window['go']['main']['App']['ScheduleSend'](arg1, arg2);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetFlagged(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetFlagged'](arg1, arg2, arg3, arg4);
}

export function SetLabel(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetLabel'](arg1, arg2, arg3, arg4, arg5);
}

export function SetNotifPrefs(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNotifPrefs'](arg1, arg2, arg3);
}

export function SetSeen(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetSeen'](arg1, arg2, arg3, arg4);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function SieveDelete(arg1, arg2) {
  return window['go']['main']['App']['SieveDelete'](arg1, arg2);
}

export function SieveGet(arg1, arg2) {
  return window['go']['main']['App']['SieveGet'](arg1, arg2);
}

export function SieveList(arg1) {
  return window['go']['main']['App']['SieveList'](arg1);
}

export function SievePut(arg1, arg2, arg3) {
  return window['go']['main']['App']['SievePut'](arg1, arg2, arg3);
}

export function SieveSetActive(arg1, arg2) {
  return window['go']['main']['App']['SieveSetActive'](arg1, arg2);
}

export function SmartCounts(arg1) {
  return window['go']['main']['App']['SmartCounts'](arg1);
}

export function SmartFolder(arg1, arg2) {
  return window['go']['main']['App']['SmartFolder'](arg1, arg2);
}

export function Translate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Translate'](arg1, arg2, arg3, arg4);
}

export function UnifiedInbox() {
  return window['go']['main']['App']['UnifiedInbox']();
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}
