// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';
import {mail} from '../models';
import {calendar} from '../models';
import {contacts} from '../models';
import {sieve} from '../models';

export function AddAccount(arg1:store.Account):Promise<store.Account>;

export function ArchiveDelete(arg1:string,arg2:string):Promise<void>;

export function ArchiveList(arg1:string):Promise<Array<main.ArchivedFile>>;

export function ArchiveOpen(arg1:string):Promise<void>;

export function ArchiveSave(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string,arg6:string):Promise<void>;

export function CachedMessages(arg1:string,arg2:string):Promise<Array<mail.Summary>>;

export function CalendarDelete(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CalendarList(arg1:string):Promise<Array<calendar.Event>>;

export function CalendarSave(arg1:string,arg2:calendar.Event):Promise<void>;

export function CancelScheduled(arg1:string):Promise<void>;

export function CheckMTASTS(arg1:string):Promise<string>;

export function CheckRecipientDANE(arg1:string,arg2:string):Promise<string>;

export function CheckRecipientTLS(arg1:string):Promise<boolean>;

export function ContactDelete(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ContactList(arg1:string):Promise<Array<contacts.Contact>>;

export function ContactSave(arg1:string,arg2:contacts.Contact):Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<void>;

export function Delete(arg1:string,arg2:string,arg3:number):Promise<void>;

export function DeleteFolder(arg1:string,arg2:string):Promise<void>;

export function ExportSettings():Promise<string>;

export function Folders(arg1:string):Promise<Array<mail.Folder>>;

export function GetAttachmentData(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Record<string, string>>;

export function GetAttachmentText(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function GetAutostart():Promise<boolean>;

export function GetWindowMode():Promise<Record<string, any>>;

export function ImportSettings(arg1:string):Promise<void>;

export function ListAccounts():Promise<Array<store.Account>>;

export function ListScheduled():Promise<Array<main.ScheduledView>>;

export function Message(arg1:string,arg2:string,arg3:number):Promise<mail.Detail>;

export function MessageSource(arg1:string,arg2:string,arg3:number):Promise<string>;

export function Messages(arg1:string,arg2:string):Promise<Array<mail.Summary>>;

export function MessagesPage(arg1:string,arg2:string,arg3:number):Promise<Array<mail.Summary>>;

export function Move(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function OpenMailWindow(arg1:number,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function PGPDecryptBody(arg1:string,arg2:string):Promise<string>;

export function PGPDeleteKey(arg1:string):Promise<void>;

export function PGPEncryptBody(arg1:string,arg2:string):Promise<string>;

export function PGPImportKey(arg1:string):Promise<main.PGPKeyInfo>;

export function PGPListKeys():Promise<Array<main.PGPKeyInfo>>;

export function PickFolder():Promise<string>;

export function Probe(arg1:string):Promise<mail.ProbeResult>;

export function RemoveAccount(arg1:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveAttachment(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function SaveDraft(arg1:mail.SendRequest,arg2:string):Promise<void>;

export function ScheduleSend(arg1:mail.SendRequest,arg2:string):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:string):Promise<Array<mail.Summary>>;

export function Send(arg1:mail.SendRequest):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetFlagged(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<void>;

export function SetLabel(arg1:string,arg2:string,arg3:number,arg4:string,arg5:boolean):Promise<void>;

export function SetNotifPrefs(arg1:boolean,arg2:string,arg3:string):Promise<void>;

export function SetSeen(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function SieveDelete(arg1:string,arg2:string):Promise<void>;

export function SieveGet(arg1:string,arg2:string):Promise<string>;

export function SieveList(arg1:string):Promise<Array<sieve.Script>>;

export function SievePut(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SieveSetActive(arg1:string,arg2:string):Promise<void>;

export function SmartCounts(arg1:string):Promise<mail.SmartCounts>;

export function SmartFolder(arg1:string,arg2:string):Promise<Array<mail.SmartSummary>>;

export function Translate(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function UnifiedInbox():Promise<Array<mail.UnifiedSummary>>;

export function UpdateAccount(arg1:store.Account):Promise<store.Account>;
